// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/ghulammuzz/misterblast/internal/question/handler"
	"github.com/ghulammuzz/misterblast/internal/question/repo"
	"github.com/ghulammuzz/misterblast/internal/question/svc"
	"github.com/go-playground/validator/v10"
)

// Injectors from wire.go:

func InitializedQuestionService(sb *sql.DB, val *validator.Validate) *handler.QuestionHandler {
	questionRepository := repo.NewQuestionRepository(sb)
	questionService := svc.NewQuestionService(questionRepository)
	questionHandler := handler.NewQuestionHandler(questionService, val)
	return questionHandler
}
