name: Main CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build_push:
    needs: test
    uses: ./.github/workflows/build_push.yaml
